### ISSUE TITLE
Edge case in shell button when launching pydm screens

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/lucid#111]
Normally you'd configure your toolbars to open pydm screens using the related display option, but at times as in #100 this hasn't worked so well so some of these are launched as shell commands.

For RIX, this unveiled another issue where opening the chemRIX vacuum screen opened the screen in a strange state. The screen would open and display ok, but whenever we tried to open any of the typhos subdisplays e.g. from the valve or gauge icons the screen would freeze and then crash.

We tried to investigate what was going on by e.g. setting redirectCommandOutput to true and by setting the log level to debug but this actually ended up causing the screen to freeze on launch altogether.

For this use case we realized that it worked find by switching back to the related display option but this seemed like bizarre behavior to me. It's not immediately clear if this is a lucid bug, an environment misconfiguration bug, a pydm bug, a typhos bug, or a pcdswidgets bug.

Configuration snippit that failed to produce a useful screen:
```
        type: shell
        redirectCommandOutput: true
        commands:
          #- pydm --hide-nav-bar --hide-menu-bar --hide-status-bar /reg/g/pcds/epics-dev/screens/pydm/vacuumscreens/screens/RIX/chemrixsVac.ui
          #- pydm --hide-nav-bar --hide-menu-bar --hide-status-bar /reg/g/pcds/epics-dev/screens/pydm/rix_screens/vacuum_screens/chemrixsVac.ui
          #- pydm --hide-nav-bar --hide-menu-bar --hide-status-bar /reg/g/pcds/epics-dev/wwright/dev_screens/chemrixsVac_new_screen.ui
          - pydm --log_level DEBUG --hide-nav-bar --hide-menu-bar --hide-status-bar /reg/g/pcds/epics-dev/wwright/dev_screens/chemrixsVac_new_screen.ui
```
```
